# Generated by Django 5.1.7 on 2025-03-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="queue",
            name="queue_number",
            field=models.CharField(
                editable=False, max_length=40, unique=True, verbose_name="队列号"
            ),
        ),
    ]
