# Generated by Django 5.1.7 on 2025-03-21 23:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0002_alter_queue_queue_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "queue_number",
                    models.CharField(max_length=40, verbose_name="队列号"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("skipped", "已过号"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="队列优先级", verbose_name="优先级"
                    ),
                ),
                (
                    "estimated_wait_time",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="预计等待时间(分钟)",
                    ),
                ),
                (
                    "actual_wait_time",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="实际等待时间(分钟)"
                    ),
                ),
                ("enter_time", models.DateTimeField(verbose_name="进入队列时间")),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始服务时间"
                    ),
                ),
                (
                    "exit_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="离开队列时间"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="备注")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="navigation.department",
                        verbose_name="科室",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="navigation.equipment",
                        verbose_name="设备",
                    ),
                ),
                (
                    "examination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="navigation.examination",
                        verbose_name="检查项目",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="navigation.patient",
                        verbose_name="患者",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="navigation.queue",
                        verbose_name="关联队列",
                    ),
                ),
            ],
            options={
                "verbose_name": "队列历史记录",
                "verbose_name_plural": "队列历史记录",
                "ordering": ["-exit_time"],
                "indexes": [
                    models.Index(
                        fields=["queue_number"], name="navigation__queue_n_65ef90_idx"
                    ),
                    models.Index(
                        fields=["status"], name="navigation__status_cbf3f3_idx"
                    ),
                    models.Index(
                        fields=["enter_time"], name="navigation__enter_t_0058bd_idx"
                    ),
                    models.Index(
                        fields=["exit_time"], name="navigation__exit_ti_9a9368_idx"
                    ),
                ],
            },
        ),
    ]
