# Generated by Django 5.1.7 on 2025-03-22 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0003_queuehistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_in_time", models.DateTimeField(verbose_name="报到时间")),
                (
                    "call_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="叫号时间"
                    ),
                ),
                (
                    "finish_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "queue_time",
                    models.IntegerField(default=0, verbose_name="排队时间(分钟)"),
                ),
                (
                    "service_time",
                    models.IntegerField(default=0, verbose_name="服务时间(分钟)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "等待中"),
                            ("called", "已叫号"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "examination_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="navigation.examination",
                        verbose_name="检查项目",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="navigation.patient",
                        verbose_name="患者",
                    ),
                ),
            ],
            options={
                "verbose_name": "队列记录",
                "verbose_name_plural": "队列记录",
                "ordering": ["check_in_time"],
            },
        ),
    ]
