# Generated by Django 5.1.7 on 2025-03-22 12:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navigation", "0004_queuerecord"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="queuehistory",
            options={"verbose_name": "队列历史", "verbose_name_plural": "队列历史"},
        ),
        migrations.AlterModelOptions(
            name="queuerecord",
            options={"verbose_name": "队列记录", "verbose_name_plural": "队列记录"},
        ),
        migrations.AddField(
            model_name="queuerecord",
            name="queue",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="navigation.queue",
                verbose_name="关联队列",
            ),
        ),
        migrations.AlterField(
            model_name="queuehistory",
            name="actual_wait_time",
            field=models.IntegerField(default=0, verbose_name="实际等待时间(分钟)"),
        ),
        migrations.AlterField(
            model_name="queuehistory",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="queuehistory",
            name="enter_time",
            field=models.DateTimeField(verbose_name="进入时间"),
        ),
        migrations.AlterField(
            model_name="queuehistory",
            name="estimated_wait_time",
            field=models.IntegerField(default=0, verbose_name="预计等待时间(分钟)"),
        ),
        migrations.AlterField(
            model_name="queuehistory",
            name="exit_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="退出时间"),
        ),
        migrations.AlterField(
            model_name="queuehistory",
            name="priority",
            field=models.IntegerField(default=0, verbose_name="优先级"),
        ),
        migrations.AlterField(
            model_name="queuehistory",
            name="queue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="navigation.queue",
                verbose_name="关联队列",
            ),
        ),
        migrations.AlterField(
            model_name="queuehistory",
            name="queue_number",
            field=models.CharField(db_index=True, max_length=20, verbose_name="队列号"),
        ),
        migrations.AlterField(
            model_name="queuehistory",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
        ),
        migrations.AlterField(
            model_name="queuehistory",
            name="status",
            field=models.CharField(db_index=True, max_length=20, verbose_name="状态"),
        ),
        migrations.AlterField(
            model_name="queuerecord",
            name="check_in_time",
            field=models.DateTimeField(verbose_name="签到时间"),
        ),
        migrations.AlterField(
            model_name="queuerecord",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="创建时间"
            ),
        ),
        migrations.AlterField(
            model_name="queuerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "等待中"),
                    ("in_service", "服务中"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                    ("no_show", "未到"),
                ],
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AddIndex(
            model_name="queuerecord",
            index=models.Index(fields=["status"], name="navigation__status_3e774a_idx"),
        ),
        migrations.AddIndex(
            model_name="queuerecord",
            index=models.Index(
                fields=["check_in_time"], name="navigation__check_i_b1015d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queuerecord",
            index=models.Index(
                fields=["call_time"], name="navigation__call_ti_0193c6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="queuerecord",
            index=models.Index(
                fields=["finish_time"], name="navigation__finish__933268_idx"
            ),
        ),
    ]
